### ISSUE TITLE
Johto Bug - 'Will get a Rattata lv 80 and beat the E4'

### ISSUE THREAD

**Issue by kingchenc** [WiWi33/Questing.lua#4]
Hello,
There is a small bug in 'Will get a Rattata lv 80 and beat the E4'
Rattata is in Team but he walk only from Pokecenter to outside Blackthorn City and back in a never ending loop

I Solved it, with walk manually to Route 45 and started bot again, and then works with no problem

**Comment by WiWi33** [comment]
Hi, be sure to have the last update, I think that I Already fixed that

**Comment by Cludch** [comment]
I think this would still not work since Pokemons are auto-evolving.
Therefore, Rattata won't stay Rattata.

**Comment by Cludch** [comment]
Another problem is that the Rattata is going to be auto-evolved.

**Comment by kingchenc** [comment]
Yes WiWi33 i have the latest Version, they stuck 100% on PokeCenter/Blackthron City  (with rattata in team, or without rattata or rattata in pc, same stuck effect), and the next Problem, the auto-evolve to ''Raticate'', after evolve  the bot lvld the Raticate to 80+ and then again stuck, because no Rattata :/ 

---> after evolve, Rattata was lvl 30, script Pushed Raticate without problems up to 80, and then, no Rattata and Script Stucked, and he Start/restart ''old'' script to get a new Rattata 

```
[23:26:17] Starting new quest: Elite 4 Johto: Will get a Rattata lv 80 and beat the E4
[23:28:02] No action executed: stopping the bot.

```

EDIT: @Khristian-kun Allright thx

**Comment by Khristian-kun** [comment]
@kingchenc the rattata is for do Joey battle quest
